
select * from pizza_sales;

/* 
KPI Requirements 
*/
--1.Total Revenue
	SELECT SUM(total_price) AS Total_Revenue FROM pizza_sales;
--2.Total Orders
	SELECT COUNT(DISTINCT order_id) AS Total_Orders FROM pizza_sales;

--3.Average Order Value
	SELECT (SUM(total_price)/COUNT(DISTINCT order_id)) AS Average_Order_Value FROM pizza_sales;

--4.Total Pizza Sold
	SELECT SUM(quantity) AS Total_Pizza_Sold FROM pizza_sales;

--5.Average Pizzas Per Order

SELECT CAST(
	CAST(SUM(quantity)AS DECIMAL(10,2)) 
	/ 
	CAST(COUNT(DISTINCT order_id) AS DECIMAL(10,2))
	AS DECIMAL(10,2))
	AS Average_Pizza_Per_Order 
	FROM pizza_sales;

/*
Queries which will provide insights For the Visualization
*/

--1.Daily Trends For Total Orders
SELECT 
	DATENAME(DW,order_date) AS Day_OF_Week,
	COUNT(DISTINCT order_id) AS Total_Order
	FROM pizza_sales 
	GROUP BY DATENAME(DW,order_date)
	ORDER BY Total_Order;

--2.Monthly Trend For Total Orders
SELECT 
	DATENAME(MONTH,order_date) AS Month_Of_Year,
	COUNT(DISTINCT order_id) AS Total_Order
	FROM pizza_sales 
	GROUP BY DATENAME(MONTH,order_date)
	ORDER BY Total_Order ASC;

--3. Quaterly Trend For Total Orders With SELECTED Quarter=1(Jan,Feb,March)
SELECT 
	DATENAME(MONTH,order_date) AS Month_Of_Year,
	COUNT(DISTINCT order_id) AS Total_Order
	FROM pizza_sales
	WHERE DATEPART(QUARTER,order_date)=1
	GROUP BY DATENAME(MONTH,order_date)
	ORDER BY Total_Order ASC;

--4. Percentage OF Sales By Pizza Category 
SELECT 
	DISTINCT(pizza_category) AS Pizza_Category,
	SUM(CAST(total_price AS DECIMAL(10,2))) AS Total_Sales,
	CAST(SUM(total_price)*100/(SELECT SUM(total_price) FROM pizza_sales) AS DECIMAL(10,2)) AS PCT
	FROM pizza_sales
	GROUP BY pizza_category
	ORDER BY PCT ASC;


--5. Percentage of Sales By Pizza Size
SELECT 
	DISTINCT(pizza_size) AS Pizza_Size,
	SUM(CAST(total_price AS DECIMAL(10,2))) AS Total_Sales,
	CAST(SUM(total_price)*100/(SELECT SUM(total_price) FROM pizza_sales) AS DECIMAL(10,2)) AS PCT
	FROM pizza_sales
	GROUP BY pizza_size
	ORDER BY PCT ASC;

--6.Percentage OF Sales By Pizza Size With Selected Month=January
SELECT 
	DISTINCT(pizza_size) AS Pizza_Size,
	SUM(CAST(total_price AS DECIMAL(10,2))) AS Total_Sales,
	CAST(SUM(total_price)*100/(SELECT SUM(total_price) FROM pizza_sales) AS DECIMAL(10,2)) AS PCT
	FROM pizza_sales
	WHERE DATEPART(MONTH,order_date)=1
	GROUP BY pizza_size
	ORDER BY PCT ASC;


--7. Highest Revenue generated by Pizza(TOP 5) With Selected Month 
SELECT
	TOP 5
	pizza_name AS Pizza_Name,
	SUM(total_price) AS Total_Revenue
	FROM pizza_sales
	WHERE DATEPART(MONTH,order_date)=4
	GROUP BY pizza_Name
	Order By Total_Revenue DESC;


--8. Lowest Revenue generated by Pizza(Bottom 5) With Selected Quarter
	SELECT
	TOP 5
	pizza_name AS Pizza_Name,
	SUM(total_price) AS Total_Revenue
	FROM pizza_sales
	WHERE DATEPART(QUARTER,order_date)=2
	GROUP BY pizza_Name
	Order By Total_Revenue ASC;

--9. Highest Selling(Quantity) Pizza Name Top 5
SELECT
	TOP 5
	pizza_name AS Pizza_Name,
	SUM(quantity) AS Total_Quantity
	FROM pizza_sales
	GROUP BY pizza_Name
	Order By Total_Quantity DESC;
	
	--By applying WHERE AND DATEPART in the query we can find value for selected Month/Quarter
	
--10. Lowest Selling (Quantity) Pizza Name (Bottom 5)
	SELECT
	TOP 5
	pizza_name AS Pizza_Name,
	SUM(quantity) AS Total_Quantity
	FROM pizza_sales
	WHERE DATEPART(QUARTER,order_date)=2
	GROUP BY pizza_Name
	Order By Total_Quantity ASC;


--11.Highest Orders Received for the Pizza (Top 5)
SELECT
	TOP 5
	pizza_name AS Pizza_Name,
	COUNT(DISTINCT order_id) AS Total_Order
	FROM pizza_sales
	GROUP BY pizza_Name
	Order By Total_Order DESC;

